### ISSUE TITLE
OPENING ERROR

### ISSUE THREAD

**Issue by ATOMATIO** [docker/awesome-compose#411]
.EXE FILE OPENING ERROR ENCOUNTER IN  L3 STAGE OF PROJECT,RECTIFY IT AND FIX IT AS SOON AS POSSIBLE
```[tasklist]
### Tasks
- [ ] https://github.com/docker/awesome-compose/pull/410
- [ ] https://github.com/docker/awesome-compose/pull/57
- [ ] https://github.com/docker/awesome-compose/issues/356
- [ ] https://github.com/docker/awesome-compose/pull/406
```

```[tasklist]
### Tasks
- [ ] https://github.com/docker/awesome-compose/pull/410
- [ ] https://github.com/docker/awesome-compose/pull/57
```
